In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("data.csv")

In [9]:
df

    price     description        date          shop
0     700        clothing  01-01-2026       raymond
1     600            food  01-02-2026   swiggy food
2     500  transportation  01-03-2026     uber ride
3     400   entertainment  01-04-2026           pvr
4     400   entertainment  01-05-2026           NaN
5     100   entertainment  01-06-2026       netflix
6      11  transportation  01-07-2026    metro card
7      12  transportation  01-08-2026          feul
8      11  transportation  01-09-2026          auto
9     134        clothing  01-10-2026         levis
10    446        clothing  01-11-2026           dlf
11     10        clothing  01-12-2026           hnm
12     10        clothing  01-12-2026     readymade
13    100            food  01-06-2026           NaN
14    100            food  01-05-2026  zomato order
15    100            food  01-11-2026        rasila
16    100            food  01-12-2026        swiggy

In [10]:
df.describe()

            price
count   17.000000
mean   219.647059
std    232.821804
min     10.000000
25%     12.000000
50%    100.000000
75%    400.000000
max    700.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   price        17 non-null     int64
 1   description  17 non-null     str
 2   date         17 non-null     str
 3   shop         15 non-null     str
dtypes: int64(1), str(3)
memory usage: 676.0 bytes

In [13]:
df.head()

   price     description        date         shop
0    700        clothing  01-01-2026      raymond
1    600            food  01-02-2026  swiggy food
2    500  transportation  01-03-2026    uber ride
3    400   entertainment  01-04-2026          pvr
4    400   entertainment  01-05-2026          NaN

In [14]:
df.head(5)

   price     description        date         shop
0    700        clothing  01-01-2026      raymond
1    600            food  01-02-2026  swiggy food
2    500  transportation  01-03-2026    uber ride
3    400   entertainment  01-04-2026          pvr
4    400   entertainment  01-05-2026          NaN

In [15]:
df.head(6)

   price     description        date         shop
0    700        clothing  01-01-2026      raymond
1    600            food  01-02-2026  swiggy food
2    500  transportation  01-03-2026    uber ride
3    400   entertainment  01-04-2026          pvr
4    400   entertainment  01-05-2026          NaN
5    100   entertainment  01-06-2026      netflix